[package]
name = "kondo"
version = "0.1.0"
edition = "2021"

[lib]
name = "kondo"
path = "src/lib.rs"

[[bin]]
name = "kondo"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
toml = { version = "0.8", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
walkdir = "2.5"
chrono = "0.4"
